Release notes for Percona XtraDB Cluster 8.0.36-28
percona/pxc-docs pull request #139
Opened 2024-03-15 16:32 UTC by alina-derkach-oaza

new file:   docs/release-notes/8.0.36-28.md
	modified:   docs/release-notes/release-notes_index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-03-22 16:14 UTC, patrickbirch approved these changes
Good
You could add the date

2024-03-25 09:25 UTC, kamil-holubicki requested changes
Additionally this ticket was included
https://perconadev.atlassian.net/browse/PXC-4340

2024-03-25 09:25 UTC, kamil-holubicki commented on docs/release-notes/8.0.36-28.md
> +* [PXC-4380](https://perconadev.atlassian.net/browse/PXC-4380): If one of the nodes in a cluster with multiple nodes (for example, 15 nodes) had network issues, the cluster could become Non-Primary.
This one was moved to 8.0.37

2024-03-25 09:25 UTC, kamil-holubicki commented on docs/release-notes/8.0.36-28.md
> +* [PXC-4277](https://perconadev.atlassian.net/browse/PXC-4277): The Percona XtraDB Cluster cluster with three nodes became inconsistent when using `ALTER .. ALGORITHM=INPLACE`.
Moved to 8.0.37

2024-03-25 09:25 UTC, kamil-holubicki commented on docs/release-notes/8.0.36-28.md
> +* [PXC-4385](https://perconadev.atlassian.net/browse/PXC-4385): When running a `TOI ALTER USER` on one node and a `SET PASSWORD` on another, the statements hung and locked the affected nodes.
Moved to 8.0.37

2024-03-25 11:35 UTC, alina-derkach-oaza commented on docs/release-notes/8.0.36-28.md
> +* [PXC-4385](https://perconadev.atlassian.net/browse/PXC-4385): When running a `TOI ALTER USER` on one node and a `SET PASSWORD` on another, the statements hung and locked the affected nodes.
Removed

2024-03-25 11:35 UTC, alina-derkach-oaza commented on docs/release-notes/8.0.36-28.md
> +* [PXC-4277](https://perconadev.atlassian.net/browse/PXC-4277): The Percona XtraDB Cluster cluster with three nodes became inconsistent when using `ALTER .. ALGORITHM=INPLACE`.
Removed

2024-03-25 11:35 UTC, alina-derkach-oaza commented on docs/release-notes/8.0.36-28.md
> +* [PXC-4380](https://perconadev.atlassian.net/browse/PXC-4380): If one of the nodes in a cluster with multiple nodes (for example, 15 nodes) had network issues, the cluster could become Non-Primary.
Removed

2024-03-28 20:59 UTC, kamil-holubicki approved these changes

2024-04-03 16:00 UTC, merged