PXC-4489 8.4.0-1 release notes and release note tasks
percona/pxc-docs pull request #175
Opened 2024-09-06 14:39 UTC by patrickbirch

modified:   docs/release-notes/8.4.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-09-09 16:31 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4034](https://perconadev.atlassian.net/browse/PXC-4034): In asynchronous replicas, using `sql_log_bin=0` disrupted the Global Transcation Identifier (GTID) consistency, causing issues with rep
Transcation -> TranSACtion

2024-09-09 16:31 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4428](https://perconadev.atlassian.net/browse/PXC-4428): In asynchronous replicas, using `sql_log_bin=0` disrupted the Global Transcation Identifier (GTID) consistency, causing issues with rep
Transcation -> TranSACtion

2024-09-09 16:31 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4362](https://perconadev.atlassian.net/browse/PXC-4362): The node could leave the cluster when binary logging was enabled and the function was created without super privilege.
Duplicated Jira. Line 39

2024-09-09 16:31 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4298](https://perconadev.atlassian.net/browse/PXC-4298): The node was disconnected when using `ALTER TABLE`, including `ADD UNIQUE` in the table containing duplicate entries (Thanks to Vit Nov
Duplicated Jira. Line 21

2024-09-09 16:31 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4348](https://perconadev.atlassian.net/browse/PXC-4348): The joiner node exited with Metadata Lock `BF-BF` conflict during `IST`.
Duplicated Jira. Line 37

2024-09-09 16:31 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4367](https://perconadev.atlassian.net/browse/PXC-4367): The InnoDB semaphore wait timeout caused a server exit under a heavy load.
Duplicated Jira. Line 45

2024-09-10 14:28 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4034](https://perconadev.atlassian.net/browse/PXC-4034): In asynchronous replicas, using `sql_log_bin=0` disrupted the Global Transcation Identifier (GTID) consistency, causing issues with rep
Global TranSCAtion Identifier (GTID) -> Global TranSACtion Identifier (GTID)

2024-09-10 14:28 UTC, alina-derkach-oaza commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4428](https://perconadev.atlassian.net/browse/PXC-4428): In asynchronous replicas, using `sql_log_bin=0` disrupted the Global Transcation Identifier (GTID) consistency, causing issues with rep
Global TranSCAtion Identifier (GTID) -> Global TranSACtion Identifier (GTID)

2024-09-12 14:25 UTC, alina-derkach-oaza approved these changes

2024-10-01 08:40 UTC, kamil-holubicki requested changes

2024-10-01 08:40 UTC, kamil-holubicki commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4041](https://perconadev.atlassian.net/browse/PXC-4041): When running `FLUSH TABLES` after a statement was prepared, the node could exit due to broken consistency.
Something wrong here

2024-10-01 08:40 UTC, kamil-holubicki commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4315](https://perconadev.atlassian.net/browse/PXC-4315): There was no Buffer Flush (BF) abort, but a message saying “Metadata Lock (MDL) conflict… solved by abort” was printed.
Brute-Force, not Bruffer Flush

2024-10-01 08:40 UTC, kamil-holubicki commented on docs/release-notes/8.4.0-1.md
> +* [PXC-4428](https://perconadev.atlassian.net/browse/PXC-4428): In asynchronous replicas, using `sql_log_bin=0` disrupted the Global Transaction Identifier (GTID) consistency, causing issues with rep
Something is wrong here. This one is about garbd. Listed below in 'bugs' section as well.

2024-10-11 08:40 UTC, kamil-holubicki approved these changes

2024-11-07 12:52 UTC, merged